config/routes.rb
MultipleImageUpload::Application.routes.draw do
  resources :pictures

  resources :galleries

   root 'galleries#index'

   get '/images' => 'galleries#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

	attr_accessible :description, :name, :pictures

  has_many :pictures, :dependent => :destroy

end

app/models/picture.rb
class Picture < ActiveRecord::Base

	attr_accessible :description, :gallery_id, :image

	belongs_to :gallery

	has_attached_file :image,
 								    :path => ":rails_root/public/images/:id/:filename",
    								:url  => "/images/:id/:filename"

	do_not_validate_attachment_file_type :image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy]

  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries
  # POST /galleries.json
  def create

=begin
    @gallery = Gallery.new(gallery_params)

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gallery }
      else
        format.html { render action: 'new' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
=end
		@gallery = Gallery.new(params[:gallery])

	  respond_to do |format|
	    if @gallery.save
	
	      if params[:images]
	        #===== The magic is here ;)
	        params[:images].each { |image|
	          @gallery.pictures.create(image: image)
	        }
	      end
	
	      format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
	      format.json { render json: @gallery, status: :created, location: @gallery }
	    else
	      format.html { render action: "new" }
	      format.json { render json: @gallery.errors, status: :unprocessable_entity }
	    end
  end
	

  end

  # PATCH/PUT /galleries/1
  # PATCH/PUT /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery.destroy
    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gallery_params
      params.require(:gallery).permit(:description, :name, :pictures)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create

		@picture = Picture.new(picture_params)

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end

=begin
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render action: 'show', status: :created, location: @picture }
      else
        format.html { render action: 'new' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
      format.json { head :no_content }
    end
  end

	
 	def make_default
    @picture = Picture.find(params[:id])
    @gallery = Gallery.find(params[:gallery_id])

    @gallery.cover = @picture.id
    @gallery.save

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:description, :gallery_id, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :pictures, :class => 'control-label' %>
    <div class="controls">
      <!-- The magic is coming ...look at my eyes....shazammmm -->
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<div class="row">
  <h1>Galleries</h1>
  <ul class="thumbnails files">
    <% @galleries.each do |gallery| %>
        <li class="span3" id="gallery_<%= gallery.id %>">
          <div class="thumbnail">
            <%= link_to image_tag(gallery.pictures.first.image.url, :size => "100x100"), gallery_path(gallery) %>
            <div class="caption">
	            <%= gallery.name.truncate(14) %> &nbsp;
              <%= link_to "Show", gallery_path(gallery) %>
              <%= link_to "Edit", edit_gallery_path(gallery) %>
              <%= link_to "Delete", gallery, :data => { :confirm => "Are you sure?" }, :method => :delete %><br><br><br>
            </div>
          </div>
        </li>
    <% end %>
  </ul>
  <%= link_to 'New', new_gallery_path, :class => 'btn btn-mini' %>
</div>

app/views/galleries/new.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  <p>
    <b>Name: </b>
    <%= @gallery.name %>
  </p>

  <p>
    <b>Description: </b>
    <%= @gallery.description %>
  </p>

<h2>Pictures</h2>
</div>

<div class="row">
  <ul class="thumbnails files">
<% unless @gallery.pictures.empty? %>
  <% @gallery.pictures.each do |pic| %>
    <li class="span3" id="picture_<%= pic.id %>">
    <div class="thumbnail">
      <div class="mag">
       <%= image_tag pic.image.url(:thumb), :size => "100x100", :'data-toggle' => "magnify" %>
      </div>
      <div class="caption">
        <%= link_to "Edit", picture_path(pic) %>
        <%= link_to "Delete", pic, :data => { :confirm => "Are you sure?" }, :method => :delete %>
      </div>
    </div>
    </li>
  <% end %>
<% end %>
</ul>
</div>

<div class="row">
  <div class="form-actions">
    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GalleryJqueryFileUpload</title>
  <%= stylesheet_link_tag "application", :media => 'all'%>
  <%= javascript_include_tag "application", :media => 'all'%>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span8"><%= link_to "Home", root_path %></div>
  </div>
  <div class="row">
    <div class="span8"><%= yield %></div>
  </div>
</div>

<div class="lessoncup">
 
<div class="btn" id="show">Show Thumbs</div>
<div class="btn" id="hide" style=" display:none;">Hide Thumbs</div>

<div class="mag">
  <div id="image"><img src="/assets/2.jpg" width="200" height="200" data-toggle="magnify"></div>
</div>
 
<div id="thumbs">
<ul>
<li style="background-image:url(/assets/1.jpg); background-repeat:no-repeat;" dir="/assets/1.jpg"></li> <br/>
<li style="background-image:url(/assets/2.jpg); background-repeat:no-repeat;" dir="/assets/2.jpg"></li> <br/>
<li style="background-image:url(/assets/3.jpg); background-repeat:no-repeat;" dir="/assets/3.jpg"></li> <br/>
<li style="background-image:url(/assets/4.jpg); background-repeat:no-repeat;" dir="/assets/4.jpg"></li> <br/>
<li style="background-image:url(/assets/5.jpg); background-repeat:no-repeat;" dir="/assets/5.jpg"></li>
</ul>
</div>
 
</div>


</body>
</html>

<script type="text/javascript" src="jquery-1.10.2.min.js"></script>
 
<script>
 
$(document).ready(function(){
  
  
 $('li').click(function(){
   
  var imgpath = $(this).attr('dir');
   
  $('#image').html('<img src='+imgpath+'>');
   
 });
  
  
 $('.btn').click(function(){
   
  $('#thumbs').fadeIn(500);
  $('#image').animate({marginTop:'10px'},200);
  $(this).hide();
   
  $('#hide').fadeIn('slow');
   
 });
  
  
 $('#hide').click(function(){
   
  $('#thumbs').fadeOut(500,function (){
  $('#image').animate({marginTop:'50px'},200);
  });
   
  $(this).hide();
  $('#show').fadeIn('slow');
   
 });
  
  
});
</script>

app/views/pictures/_form.html.erb
<%= form_for [@gallery, @picture], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>

		<%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture, :class => 'file_field' %>
    </div>
  </div>
 
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>
  </div>

<% end %>

app/views/pictures/destroy.js.erb
$('#picture_<%= @picture.id %>').fadeOut();

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<%- model_class = Picture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= picture.description %></td>
        <td><%= image_tag picture.image.url %></td>
        <td><%= picture.gallery_id %></td>
        <td><%= picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/make_default.js.erb
$('<span style="color: #46a546; margin-left: 15px; font-weight: bold;">Done!</span>').insertAfter('#make_default').delay(3000).fadeOut('slow');

app/views/pictures/new.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= image_tag @picture.image.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= @picture.gallery_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>